---
booktitle: AAAI Workshop on Meta-Learning and MetaDL Challenge
shortname: MetaDL
volume: '140'
year: '2021'
start: 2021-02-09
end: 2021-02-09
published: 2021-08-18
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MetaDL
month: 0
cycles: false
bibtex_editor: Guyon, Isabelle and van Rijn, Jan N. and Treguer, S\'{e}bastien and
  Vanschoren, Joaquin
editor:
- given: Isabelle
  family: Guyon
- given: Jan N.
  family: Rijn
  prefix: van
- given: Sébastien
  family: Treguer
- given: Joaquin
  family: Vanschoren
title: Proceedings of Machine Learning Research
description: |
  AAAI Workshop on Meta-Learning and MetaDL Challenge
    Held in Virtual on 09 February 2021

  Published as Volume 140 by the Proceedings of Machine Learning Research on 18 August 2021.

  Volume Edited by:
    Isabelle Guyon
    Jan N. van Rijn
    Sébastien Treguer
    Joaquin Vanschoren

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: '09 Feb'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v140"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v140
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v140
email: ''
conference:
  name: AAAI Workshop on Meta-Learning and MetaDL Challenge
  url: https://aaai.org/Conferences/AAAI-21/ws21workshops/#ws18
  location: Virtual
  dates:
  - 2021-02-09
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v140/MetaDL.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v140/MetaDL.bib
